name: npapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.2
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3
  cloud_firestore: ^6.1.1
  firebase_database: ^12.1.1
  firebase_storage: ^13.0.5
  file_picker: ^10.3.8
  flutter_pdfview: ^1.4.3
  syncfusion_flutter_pdfviewer: ^31.1.19

  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.5.3
  firebase_messaging: ^16.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  build_runner: ^2.5.4
  path_provider: ^2.1.5
  dio: ^5.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  generate: true   # <-- IMPORTANT: enables code generation for l10n
  uses-material-design: true

  assets:
    - lib/assets/svg/
    - lib/l10n/
